# Created on Monday May 11 2020
#
# Authored by Joanna Leng who works at the University of Leeds who is funded by
# EPSRC as a Research Software Engineering Fellow (EP/R025819/1) for the PERPL
# project.
# Modified by Alistair Curd, Peckham Group, University of Leeds, who is funded by
# BBSRC grant BB/S015787/1.

# ---
# Copyright 2020 Peckham Lab
#
# Licensed under the Apache License, Version 2.0 (the "License"); you may not use
# this file except in compliance with the License. You may obtain a copy of the
# License at
# http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software distributed
# under the License is distributed on an "AS IS" BASIS, WITHOUT WARRANTIES OR
# CONDITIONS OF ANY KIND, either express or implied. See the License for the
# specific language governing permissions and limitations under the License.
#
name: PERPL
channels:
  - defaults
  - conda-forge
dependencies:
  - python=3.7
  - matplotlib=3.1.*
  - numdifftools=0.9.*
  - numpy=1.16
  - pandas=1.0.*
  - scipy=1.3.*
  - scikit-image=0.16.2
  - spyder
  - pip=19.1
  - jupyter
  - nbstripout
  - doxygen=1.8
